apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: github-template
  namespace: default
spec:
  params:
    - name: gitrevision
      description: The git revision
    - name: gitrepositoryurl
      description: The git repository url
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: tekton-pipelinerun
        namespace: default
      spec:
        serviceAccountName: dockerhub-service-account
        pipelineRef:
          name: tekton-pipeline
        podTemplate:
          securityContext:
            fsGroup: 65532
        params:
          - name: repo-url
            value: "$(tt.params.gitrepositoryurl)"
          - name: image-reference
            value: vigneshvicky12345/maven
          - name: image-tag
            value: "$(tt.params.gitrevision)"
        workspaces:
          - name: tekton-workspace
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 25Gi
